mode: structure
data_file: matbench_mp_gap.pt

epochs: 600
batch_size: 16          # ⬅️ 如果显存允许
patience: 150

lr: 1.2e-4
weight_decay: 0.001
loss: huber

embed_dim: 512
dropout: 0.1
use_amp: true

struct_config:
  conv_layers: 3
  graphormer_layers: 1  # ⭐ 关键提速点
  node_dim: 128
  num_heads: 4
  ff_hidden: 256